#%RAML 1.0 Trait
headers:
  X-Cms-ClientId:
    required: true
    type: string
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbdcefbvh"
  X-Cms-ClientSecret:
    required: true
    type: string
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd53tw6g"